import { Project } from '@/types';

export const projects: Project[] = [
  {
    id: '8',
    title: 'Malin Market',
    description: 'A stall-rental platform for a 406-stall, 12-zone market in front of Chiang Mai University — vendors browse an interactive market map, check live availability, and request a stall in a few steps, while the team manages tenants and bookings from one admin system. Built end to end as a solo engineer, owning both development and infrastructure — from a pnpm monorepo of a Next.js frontend, a NestJS API with LINE Login, and a shared Prisma data layer, to a containerized stack on AWS EC2: Docker Compose services behind a Caddy reverse proxy, PostgreSQL 16 persisted on a Docker volume, and a GitHub Actions pipeline that gates every release on Playwright E2E tests, pushes images to GitHub Container Registry, and deploys over SSH, all fronted by Cloudflare. The timeline was cut from 25 days to 14 as the launch date kept moving up, and the platform still shipped to production on schedule.',
    type: 'production',
    image: '/assets/malinmarket.png',
    techStack: ['Next.js', 'NestJS', 'TypeScript', 'Tailwind', 'Prisma', 'PostgreSQL', 'Docker', 'Caddy', 'AWS EC2', 'GitHub Actions', 'Playwright', 'Cloudflare', 'LINE Login'],
    githubUrl: undefined,
    liveUrl: 'https://malinmarket.com/',
  },
  {
    id: '9',
    title: 'Nippon Store',
    description: 'A promotional landing page for Nippon Store, a Japanese-owned shop in Chiang Mai importing authentic snacks, drinks, and groceries from Japan. Built to give the shop a real online presence — a trilingual Thai / English / Japanese site that showcases products by category and sends customers straight to the Shopee storefront and Facebook page.',
    type: 'production',
    image: '/assets/nippon.png',
    techStack: ['Next.js', 'TypeScript', 'Tailwind', 'i18n', 'Vercel'],
    githubUrl: undefined,
    liveUrl: 'https://nippon-five.vercel.app/',
  },
  {
    id: '6',
    title: 'Hylife IT Asset Management',
    description: 'An internal IT asset management system built for Hylife, covering the full lifecycle of company hardware and equipment — registration, assignment, tracking, and maintenance history — through complete CRUD workflows. Built with Next.js on the frontend and NestJS with PostgreSQL on the backend, deployed on AWS EC2 behind Nginx with PM2 process management.',
    type: 'production',
    image: '/assets/hylife-assets-placeholder.png',
    techStack: ['Next.js', 'NestJS', 'PostgreSQL', 'AWS EC2', 'PM2', 'Nginx'],
    githubUrl: undefined,
    liveUrl: undefined,
  },
  {
    id: '7',
    title: 'Enterprise AI Agentic Platform',
    description: 'An enterprise-grade agentic AI platform that gives every department its own multi-agent workflows. Designed the agentic workflow architecture — orchestrator agents delegating to specialized sub-agents per department — together with an AI gateway that routes each request between local AI models and cloud AI providers based on configurable rules for cost, privacy, and capability.',
    type: 'production',
    image: '/assets/ai-agentic-placeholder.png',
    techStack: ['Multi-Agent', 'Sub-Agents', 'AI Gateway', 'Local LLM', 'Cloud AI'],
    githubUrl: undefined,
    liveUrl: undefined,
  },
  {
    id: '1',
    title: 'Ninja Lingo',
    description: 'NinjaLingo is a vocabulary learning web application focused on enhancing memorization and retention through interactive learning techniques. Designed with a clean and intuitive interface, the platform helps users efficiently build and reinforce vocabulary in an engaging way.',
    type: 'production',
    image: "/assets/ninjalingo.png",
    techStack: ['React', 'TypeScript', 'Tailwind', 'Astro', 'Neon'],
    githubUrl: undefined,
    liveUrl: 'https://ninjalingo.com',
  },
  {
    id: '2',
    title: 'TurnPro Landing page',
    description: 'A modern web application designed with a strong focus on SEO, performance, and scalability. Built using lightweight architecture to ensure fast load times, improved Core Web Vitals, and seamless user experience. Optimized for search engine visibility with clean structure, semantic HTML, and best practices for indexing and ranking.',
    type: 'production',
    image: "/assets/turnpro.png",
    techStack: ['Next.js', 'TypeScript', 'Tailwind', 'Slug', 'Non SQL'],
    githubUrl: undefined,
    liveUrl: 'https://turnprolandingpage.vercel.app/',
  },
  {
    id: '3',
    title: 'CMU Torch',
    description: 'A cross-platform mobile application developed with React Native, designed to support the well-being of Chiang Mai University students. The app acts as a close companion, providing personalized guidance for both physical and mental health. It offers consistent support through daily check-ins, health recommendations, and emotional encouragement, helping students build healthier habits and maintain a balanced lifestyle.',
    type: 'academic',
    image: "/assets/cmu-torch.png",
    techStack: ['React-native', 'Supabase', 'API-CMU', 'Tailwind'],
    githubUrl: 'https://github.com/NFil2st/CMU-Torch',
    liveUrl: undefined,
  },
  {
    id: '4',
    title: 'Script & Model GTA FiveM',
    description: 'Developed a FiveM vehicle handling configuration using Lua, including a complete handling script and vehicle model integration. The project focuses on optimizing driving performance, balancing speed, control, and stability for an enhanced in-game experience. The handling setup is ready-to-use and designed to be easily integrated into FiveM servers, ensuring smooth gameplay and realistic vehicle behavior across different driving conditions.',
    type: 'opensource',
    image: "/assets/handling-fivem.jpg",
    techStack: ['Lua'],
    githubUrl: 'https://github.com/bookbento/Handling-Cars-GTAV',
    liveUrl: undefined,
  },
  {
    id: '5',
    title: 'Check in-out TurnPro',
    description: 'Developed TurnPro, a fully React-based web application designed for employee check-in and check-out management. The system enables staff to easily record their working hours in real-time, improving attendance tracking and operational efficiency. The application features a clean and responsive interface, ensuring a seamless user experience across devices, while providing accurate time logging and reliable data management for the organization.',
    type: 'personal',
    image: "/assets/checkin-out.png",
    techStack: ['React', 'Tailwind'],
    githubUrl: 'https://github.com/bookbento/Check_in-out_TurnPro',
    liveUrl: undefined,
  },
  {
    id: '10',
    title: 'One Piece TCG Gacha',
    description: 'A fan-made, free-to-play One Piece Card Game pull cabinet built out of personal passion to play with friends — everyone draws from the same shared cabinet, and the latest pulls show up for the whole group live. No real money involved, just the fun of opening packs together. Around 10 friends have already played it for real.',
    type: 'personal',
    image: '/assets/tcgonepiece.png',
    techStack: ['TypeScript', 'Supabase', 'Vercel'],
    githubUrl: undefined,
    liveUrl: 'https://tcgonepiece.vercel.app/',
  },

];