import { Project } from '@/types';

export const projects: Project[] = [
  {
    id: '1',
    title: 'Ninja Lingo',
    description: 'NinjaLingo is a vocabulary learning web application focused on enhancing memorization and retention through interactive learning techniques. Designed with a clean and intuitive interface, the platform helps users efficiently build and reinforce vocabulary in an engaging way.',
    type: 'production',
    image: "/assets/ninjalingo.png",
    techStack: ['React', 'TypeScript', 'Tailwind', 'Astro', 'Neon'],
    githubUrl: undefined,
    liveUrl: 'https://ninjalingo.com',
  },
  {
    id: '2',
    title: 'TurnPro Landing page',
    description: 'A modern web application designed with a strong focus on SEO, performance, and scalability. Built using lightweight architecture to ensure fast load times, improved Core Web Vitals, and seamless user experience. Optimized for search engine visibility with clean structure, semantic HTML, and best practices for indexing and ranking.',
    type: 'production',
    image: "/assets/turnpro.png",
    techStack: ['Next.js', 'TypeScript', 'Tailwind', 'Slug', 'Non SQL'],
    githubUrl: undefined,
    liveUrl: 'https://turnprolandingpage.vercel.app/',
  },
  {
    id: '3',
    title: 'CMU Torch',
    description: 'A cross-platform mobile application developed with React Native, designed to support the well-being of Chiang Mai University students. The app acts as a close companion, providing personalized guidance for both physical and mental health. It offers consistent support through daily check-ins, health recommendations, and emotional encouragement, helping students build healthier habits and maintain a balanced lifestyle.',
    type: 'academic',
    image: "/assets/cmu-torch.png",
    techStack: ['React-native', 'Supabase', 'API-CMU', 'Tailwind'],
    githubUrl: 'https://github.com/NFil2st/CMU-Torch',
    liveUrl: undefined,
  },
  {
    id: '4',
    title: 'Script & Model GTA FiveM',
    description: 'Developed a FiveM vehicle handling configuration using Lua, including a complete handling script and vehicle model integration. The project focuses on optimizing driving performance, balancing speed, control, and stability for an enhanced in-game experience. The handling setup is ready-to-use and designed to be easily integrated into FiveM servers, ensuring smooth gameplay and realistic vehicle behavior across different driving conditions.',
    type: 'opensource',
    image: "/assets/handling-fivem.jpg",
    techStack: ['Lua'],
    githubUrl: 'https://github.com/bookbento/Handling-Cars-GTAV',
    liveUrl: undefined,
  },
  {
    id: '5',
    title: 'Check in-out TurnPro',
    description: 'Developed TurnPro, a fully React-based web application designed for employee check-in and check-out management. The system enables staff to easily record their working hours in real-time, improving attendance tracking and operational efficiency. The application features a clean and responsive interface, ensuring a seamless user experience across devices, while providing accurate time logging and reliable data management for the organization.',
    type: 'personal',
    image: "/assets/checkin-out.png",
    techStack: ['React', 'Tailwind'],
    githubUrl: 'https://github.com/bookbento/Check_in-out_TurnPro',
    liveUrl: undefined,
  },

];